version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: edward
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: novel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"
volumes:
  mysql_data:
